# Generated by Django 4.1.5 on 2023-01-19 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subtitulosGPT', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filesrtupload',
            name='file',
        ),
    ]
