# Generated by Django 4.1.5 on 2023-01-19 08:56

from django.db import migrations, models
import subtitulosGPT.models


class Migration(migrations.Migration):

    dependencies = [
        ('subtitulosGPT', '0002_remove_filesrtupload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesrtupload',
            name='file',
            field=models.FileField(default='', upload_to='uploads/', validators=[subtitulosGPT.models.validate_file_extension]),
            preserve_default=False,
        ),
    ]
