# Generated by Django 4.1.5 on 2023-01-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('sugerenciaGenerada', models.BooleanField(verbose_name=False)),
                ('mensaje', models.CharField(max_length=1500)),
                ('sugerencias', models.CharField(max_length=1500)),
            ],
        ),
    ]
