# Generated by Django 4.1.5 on 2023-01-25 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chileanRut', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='infoRecibida',
            field=models.BooleanField(default=False),
        ),
    ]
