# Generated by Django 4.1.5 on 2023-04-16 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hidroponiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumo',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
