# Generated by Django 4.1.5 on 2023-01-17 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Condimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Consistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Hora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='InstruccionesEspecifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Paso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempoMinutos', models.PositiveIntegerField()),
                ('Temperatura', models.PositiveIntegerField(blank=True)),
                ('CondimentoEspecia', models.ManyToManyField(blank=True, to='recetasApp.condimento')),
                ('ConsistenciaDeseada', models.ManyToManyField(blank=True, to='recetasApp.consistencia')),
                ('accion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recetasApp.accion')),
            ],
        ),
        migrations.CreateModel(
            name='SaboresGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Utensilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publica', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=30)),
                ('porciones', models.PositiveIntegerField()),
                ('hora', models.ManyToManyField(to='recetasApp.hora')),
                ('saborGeneral', models.ManyToManyField(to='recetasApp.saboresgeneral')),
            ],
        ),
        migrations.CreateModel(
            name='PasoIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recetasApp.ingrediente')),
                ('paso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recetasApp.paso')),
            ],
        ),
        migrations.AddField(
            model_name='paso',
            name='ingredientes',
            field=models.ManyToManyField(through='recetasApp.PasoIngrediente', to='recetasApp.ingrediente'),
        ),
        migrations.AddField(
            model_name='paso',
            name='instruccionEspecifica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recetasApp.instruccionesespecifica'),
        ),
        migrations.AddField(
            model_name='paso',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recetasApp.receta'),
        ),
        migrations.AddField(
            model_name='paso',
            name='utensilio',
            field=models.ManyToManyField(to='recetasApp.utensilio'),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recetasApp.unidade'),
        ),
    ]
